jobs:
- job: 'Test'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'

  steps:
  - task: PythonScript@0
    inputs:
      targetType: 'inline'
      script: |
        python manage.py test